version: '3'
services:    
    node:
        build: 
            context: .
        restart: always
        volumes:
            - ./html/index.html:/home/user/nodeunblocker.com/public/index.html
        expose:
            - "8080"
    http:
        build: 
            context: .
            dockerfile: dockerfile-http
        restart: always    
        ports:
            - 80:80
        volumes:
            - ./nginx/ketnoiso.conf:/etc/nginx/sites-enabled/ketnoiso.conf # change site.com (!)
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf