version: '3'
services:    
    node:
        build: 
            context: .
        restart: always    
        expose:
            - "8080"
    http:
        build: 
            context: .
            dockerfile: dockerfile-http
        restart: always    
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
            - ./certbot/www:/var/www/html
    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            # - certbot-var:/var/lib/letsencrypt
            - ./certbot/www:/var/www/html
        depends_on:
            - http
        command: certonly --webroot --webroot-path=/var/www/html --email contact@ketnoiso.net --agree-tos --no-eff-email --force-renewal -d app.ketnoiso.net